# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

BOX_IMAGE = "ubuntu/bionic64"



Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"


  config.vm.define :master, primary: true do |master|
    master.vm.box = BOX_IMAGE
    master.vm.hostname = "master"

    master.vm.network :private_network, ip: "192.168.33.10"

    master.vm.provider "virtualbox" do |vb|
      vb.gui = false

      vb.name = "lamp_master"
      vb.memory = "2048"
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end

  config.vm.define :webserver do |webserver|
    webserver.vm.box = BOX_IMAGE
    webserver.vm.hostname = "webserver"

    webserver.vm.network :private_network, ip: "192.168.33.11"

    webserver.vm.provider "virtualbox" do |vb|
      vb.gui = false

      vb.name = "lamp_webserver"
      vb.memory = "2048"
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end

  config.vm.define :db do |db|
    db.vm.box = BOX_IMAGE
    db.vm.hostname = "db"

    db.vm.network :private_network, ip: "192.168.33.12"

    db.vm.provider "virtualbox" do |vb|
      vb.gui = false

      vb.name = "lamp_db"
      vb.memory = "2048"
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
#  config.vm.provider "virtualbox" do |vb|
#    # Display the VirtualBox GUI when booting the machine
#    vb.gui = false
#
#    vb.name = "lamp"
#    vb.memory = "2048"
#    vb.cpus = 2
#    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
#    vb.customize ["modifyvm", :id, "--ioapic", "on"]
#  end

#  # Ansible provisioner.
#  config.vm.provision "ansible" do |ansible|
#    #ansible.compatibility_mode = "2.0"
#    ansible.playbook = "playbook.yml"
#    #ansible.inventory_path = "inventory"
#    ansible.become = true
#    ansible.verbose = "v"
#  end

end
