---
### Docker installation

- name: add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
  register: dockerrepo

- name: apt repositories update
  when: dockerrepo.changed
  apt:
    update_cache: yes

- name: install Docker packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: no
    force_apt_get: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: setup Docker service
  systemd:
    name: docker
    daemon_reload: yes
    enabled: yes
    state: started

- name: daemon config file
  copy:
    src: roles/docker/files/daemon.json
    dest: /etc/docker/daemon.json
    force: no
  notify: restart Docker daemon

- import_tasks: python_modules.yml

# vi: set expandtab:
