---
### handlers for base role

- name: restart firewall
  service:
    name: netfilter-persistent
    state: restarted

- name: restart ntp
  service:
    name: ntp
    state: restarted

# vi: set expandtab:
