---
### Base tasks for Ubuntu 18.04 LTE

- import_tasks: base-packages.yml
- import_tasks: base-firewall.yml

- name: NTP setup - systemd-timesyncd.service
  service:
    name: systemd-timesyncd.service
    state: stopped
    enabled: no
- name: NTP setup - packages installation
  apt: name=ntp state=latest
- name: NTP setup - initial config
  register: ntpsetup
  copy:
    src: templates/ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
- name: NTP setup - restart
  when: ntpsetup.changed
  service: name=ntp state=restarted

- name: environment setup - screenrc
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items: 
   - { src: 'templates/vimrc', dest: '/root/.vimrc' }
   - { src: 'templates/screenrc', dest: '/root/.screenrc' }
   - { src: 'templates/screenrc', dest: '/etc/skel/.screenrc' }
   - { src: 'templates/tmout.sh', dest: '/etc/profile.d/tmout.sh' }

# vi: set expandtab:
