- hosts: all
  remote_user: root
  become: yes
  tasks:
  - name: standard packeges
    apt:
      name: "{{ packages }}"
      state: latest
      autoclean: yes
      autoremove: yes
      update_cache: yes
    vars:
      packages:
      - mc
      - postfix
      - unzip
      - zip
      - apt-file
      - apt-show-versions
      - lynx
      - elinks
      - sysstat
      - apparmor-utils
      - htop
      - screen
      - apt-transport-https
      - wget

  - name: firewall setup - ufw removal
    apt:
      name: ufw
      state: absent
      purge: yes
  - name: firewall setup - packages installation
    apt:
      name: [iptables-persistent, netfilter-persistent]
      state: latest
  - name: firewall setup - initial config
    register: firewalsetup
    copy:
      src: templates/rules.v4
      dest: /etc/iptables/rules.v4
      owner: root
      group: root
      mode: 0644
  - name: firewall setup - restart
    when: firewalsetup.changed
    service: name=netfilter-persistent state=restarted

  - name: NTP setup - systemd-timesyncd.service
    service:
      name: systemd-timesyncd.service
      state: stopped
      enabled: no
  - name: NTP setup - packages installation
    apt: name=ntp state=latest
  - name: NTP setup - initial config
    register: ntpsetup
    copy:
      src: templates/ntp.conf
      dest: /etc/ntp.conf
      owner: root
      group: root
      mode: 0644
  - name: NTP setup - restart
    when: ntpsetup.changed
    service: name=ntp state=restarted

  - name: environment setup - screenrc
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items: 
     - { src: 'templates/vimrc', dest: '/root/.vimrc' }
     - { src: 'templates/screenrc', dest: '/root/.screenrc' }
     - { src: 'templates/screenrc', dest: '/etc/skel/.screenrc' }
     - { src: 'templates/tmout.sh', dest: '/etc/profile.d/tmout.sh' }

# vi: set expandtab:
