---

- name: etckeeper installation
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: no
    force_apt_get: yes
  vars:
    packages:
    - git
    - etckeeper

# vi: set expandtab:
