---
### Main config for Ubuntu 18.04 LTS server by Ser@fin

- hosts: all
  remote_user: root
  become: yes
  vars:
    zabbixserver: 127.1.1.1
    firewall_opentcpports: 80,9200,9300
  roles:
    - base
    - zabbix-agent
    - etckeeper

- hosts: elasticsearch
  remote_user: root
  become: yes
  vars:
    elasticsearch_clustername: test-elk-cluster
    elasticsearch_discovery: '[ "192.168.33.10", "192.168.33.11" ]'
  roles:
    - elasticsearch

#- hosts: logstash
#  remote_user: root
#  become: yes
#  vars:
#    elastictarget: "192.168.33.10:9200"
#    jvmheapsize: 512m
#  roles:
#    - logstash

- hosts: kibana
  remote_user: root
  become: yes
  vars:
    kibana_host2proxy: "127.0.0.1:5601"
    kibana_vhost: "192.168.33.11"
    kibana_name: "kibana-test"
    kibana_basepath: "/kibana"
    kibana_elasticsearchhosts: '[ "http://192.168.33.10:9200", "http://192.168.33.11:9200" ]'
  roles:
    - kibana

- hosts: elastalert
  remote_user: root
  become: yes
  vars:
  roles:
    - docker
    - elastalert

# vi: set expandtab
