---
### Main config for Ubuntu 18.04 LTS server by Ser@fin

- hosts: all
  remote_user: root
  become: yes
  vars:
    zabbixserver: 127.1.1.1
    elkclustername: test-elk-cluster
  roles:
    - base
    - zabbix-agent
    - etckeeper

- hosts: elasticsearch
  vars:
    elkclustername: test-elk-cluster
  roles:
    - elasticsearch
    - logstash

# vi: set expandtab:
