all:
  hosts:
    node1:
      ansible_port: 2222
      ansible_host: 127.0.0.1
      ansible_user: vagrant
      ansible_python_interpreter: /usr/bin/python3
    node2:
      ansible_port: 2200
      ansible_host: 127.0.0.1
      ansible_user: vagrant
      ansible_python_interpreter: /usr/bin/python3

# vi: set expandtab:
