all:
  hosts:
    node1:
      ansible_port: 2222
    node2:
      ansible_port: 2200
  vars:
    ansible_host: 127.0.0.1
    ansible_user: vagrant
    ansible_python_interpreter: /usr/bin/python3
  children:
    elastic:
      hosts:
        node1:
        node2:
      vars:
        jvm_mem: 512m
    kibana:
      hosts:
        node1:
      vars:
        kibanavar: asd

# vi: set expandtab:
