all:
  hosts:
    node1:
      ansible_host: 192.168.33.10
    node2:
      ansible_host: 192.168.33.11
  vars:
    ansible_user: vagrant
    ansible_port: 22
    ansible_python_interpreter: /usr/bin/python3
  children:
    elasticsearch:
      hosts:
        node1:
        node2:
      vars:
        jvmheapsize: 512m
    logstash:
      hosts:
        node1:
    kibana:
      hosts:
        node2:
      vars:
        kibanavar: asd

# vi: set expandtab:
