# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

BOX_IMAGE = "ubuntu/bionic64"

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.ssh.insert_key = false
  config.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys", run: "once"

  config.vm.define :node1, primary: true do |node1|
    node1.vm.box = BOX_IMAGE
    node1.vm.hostname = "elk-node1"

    node1.vm.network :private_network, ip: "192.168.33.10"

    node1.vm.provider "virtualbox" do |vb|
      vb.gui = false

      vb.name = "elk_node1"
      vb.memory = "2048"
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end

  end

  config.vm.define :node2 do |node2|
    node2.vm.box = BOX_IMAGE
    node2.vm.hostname = "elk-node2"

    node2.vm.network :private_network, ip: "192.168.33.11"

    node2.vm.provider "virtualbox" do |vb|
      vb.gui = false

      vb.name = "elk_node2"
      vb.memory = "2048"
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end

  end

  config.vm.define :node3 do |node3|
    node3.vm.box = BOX_IMAGE
    node3.vm.hostname = "elk-node3"

    node3.vm.network :private_network, ip: "192.168.33.12"

    node3.vm.provider "virtualbox" do |vb|
      vb.gui = false

      vb.name = "elk_node3"
      vb.memory = "2048"
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end

  end

  # packages database update, to speed-up ansible playbook execution
  config.vm.provision "shell", inline: "apt-get -q update", run: "once"

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "elk.yml"
    ansible.inventory_path = "hosts.yml"
    #ansible.verbose = "v"
  end

end
