---

- import_tasks: elasticrepo.yml
- import_tasks: jre.yml

- name: installing elasticsearch package
  apt:
    name: elasticsearch
    state: present
    force_apt_get: yes

- import_tasks: elastic-config.yml

- name: configure elasticsearch instance - JVM heap size
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    regexp: '^-Xms'
    line: "-Xms{{ jvmheapsize }}"

- name: configure elasticsearch instance - JVM max heap size
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    regexp: '^-Xmx'
    line: "-Xmx{{ jvmheapsize }}"

- name: setup elasticsearch service
  systemd:
    name: elasticsearch
    daemon_reload: yes
    enabled: yes
    #state: restarted
    state: started

# vi: set expandtab: set noai:
