---

- import_tasks: elasticrepo.yml
- import_tasks: jre.yml

- name: installing elasticsearch package
  apt:
    name: elasticsearch
    state: latest

- name: configure elasticsearch instance - cluster name
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^[#\s]?cluster.name:'
    line: 'cluster.name: {{ elkclustername }}'

- name: configure elasticsearch instance - node name
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^[#\s]?node.name:'
    line: "node.name: {{ ansible_hostname }}"

- name: configure elasticsearch instance - network host
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^[#\s]?network.host:'
    line: "network.host: {{ ansible_all_ipv4_addresses[1] }}"

- name: configure elasticsearch instance - discovery settings
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^[#\s]?discovery.zen.ping.unicast.hosts:'
    line: "discovery.zen.ping.unicast.hosts: [{% for host in groups['elasticsearch'] %} \"{{ hostvars[host].ansible_all_ipv4_addresses[1] }}\", {% endfor %}"

- name: configure elasticsearch instance - discovery settings2
  replace:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^([#\s]?discovery.zen.ping.unicast.hosts:.+),\s?$'
    replace: '\1 ]'

- name: configure elasticsearch instance - JVM heap size
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    regexp: '^-Xms'
    line: "-Xms{{ jvmheapsize }}"

- name: configure elasticsearch instance - JVM max heap size
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    regexp: '^-Xmx'
    line: "-Xmx{{ jvmheapsize }}"


- name: setup elasticsearch service
  systemd:
    name: elasticsearch
    daemon_reload: yes
    enabled: yes
    state: restarted







# vi: set expandtab: set noai:
