---

all:
  hosts:
    windows:
      ansible_user: vagrant
      ansible_password: vagrant
      ansible_connection: winrm
      ansible_winrm_transport: basic
      ansible_host: 192.168.5.164
      ansible_port: 5985

# vi:set expandtab
