---
### NTP server setup

- name: NTP setup - systemd-timesyncd.service
  service:
    name: systemd-timesyncd.service
    state: stopped
    enabled: no

- name: NTP setup - packages installation
  apt:
    name: ntp
    state: present
    force_apt_get: yes

- name: NTP setup - initial config
  register: ntpsetup
  copy:
    src: roles/base/files/ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify: restart ntp

# vi: set expandtab:
