---
### Base packages for Ubuntu OS

- name: standard packeges
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: no
    force_apt_get: yes
  vars:
    packages:
    - mc
    - postfix
    - unzip
    - zip
    - apt-file
    - apt-show-versions
    - lynx
    - elinks
    - sysstat
    - apparmor-utils
    - htop
    - screen
    - apt-transport-https
    - wget
    - ca-certificates
    - curl
    - software-properties-common

- name: unattended upgrades to be disabled
  systemd:
    name: unattended-upgrades
    state: stopped
    enabled: no
#  command: "{{ item }}"
#  with_items:
#  - systemctl stop unattended-upgrades
#  - systemctl disable unattended-upgrades

# vi: set expandtab:
